name: "Deploying Backend Infrastructure in AWS"

on:
  workflow_dispatch:

jobs:
  deploy:
    name: "Provision Infrastructure"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          # terraform_version: 1.4.2
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

  Test:
    name: "End-to-end Test"
    runs-on: ubuntu-22.04
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          working-directory: my-resume-spec.cy.js
          build: npx cypress info